name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t "${DOCKERHUB_USERNAME}/test-image:${{github.sha}}" .
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN}
          docker push "${DOCKERHUB_USERNAME}/test-image:${{github.sha}}"

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"

      - name: Some task that fetches dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ./fetch-deps.sh

      - name: clone and update
        run: |
          git clone https://swathiwohlig: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@github.com/swathiwohlig/DevOps-Assessment.git
          cd DevOps-Assessment
          yq e '.spec.template.spec.containers[0].image = "swathiwohlig/helloworld-img:${{ github.sha }}"' -i ./nginx-deployment.yml
          git config --global user.email "swathi.wohlig@wohlig.com"
          git config --global user.name "swathiwohlig"
          git add .
          git commit -m "updated"
          git push -u git@github.com:swathiwohlig/DevOps-Assessment.git main
